### PR TITLE
Refactor CMake build using newer practices.

### PR DESCRIPTION
**Pull request by jdeaton**
As part of putting together a Spack package for MAST I decided to try to take a cut at modernizing the CMake build process. I'm basing this on guidance I found in https://crascit.com/professional-cmake/, which seems to be and one of the few modern references of CMake I can find. The author is one of the primary contributors to CMake.

This branch starts from the MAST source tree and shows the outline for possibly a cleaner CMake implementation. I've currently only setup the basic CMakeLists.txt's, some modules for finding dependencies, a skeleton of the MAST library with only a few files pulled into the build, and a basic dummy example that links it all together.

Let me know what you think. I believe if I keep just pushing changes to this pull request and it will keep updating and we can discuss.

### CODE REVIEW

**Comment by jdeaton** [comment]
Also, I'm building/running as follows from inside the root of the MAST repo using dependencies built all from Spack. The mainline Spack accepted my pull request for a libMesh variant with SLEPc and recent versions. You can give it a try if you want with `spack install libmesh+slepc ^petsc~int64+mpi+suite-sparse+mumps`.

```
mkdir build2
cd build2
cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpifort -DlibMesh_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/libmesh-1.3.0-p5doeomab6c2lhay7ccxbglep4u7x44l -DPETSc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/petsc-3.9.3-e2zmceiit7nmkmtoohxv62dicnaqktf5 -DSLEPc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/slepc-3.9.1-24qjtyghv5yiizplwrfygywnjnxilk2t
make
ex/ex1_axial_bar_extension/ex1_axial_bar_extension 
```

Obviously not a fully functional library or example, just possible reorganized build process.

**Comment by jdeaton** [comment]
Most recent commit gives us a build target for generating Doxygen API documentation with CMake option `BUILD_DOC`. I think we can extend this later to do something like deal-ii with generating html out of example source files as well.

Everything worked for me with:
```
mkdir build2
cd build2
cmake .. \
-DCMAKE_C_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpicc \
-DCMAKE_CXX_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpicxx \
-DCMAKE_Fortran_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpifort \
-DlibMesh_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/libmesh-1.3.0-p5doeomab6c2lhay7ccxbglep4u7x44l \
-DPETSc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/petsc-3.9.3-e2zmceiit7nmkmtoohxv62dicnaqktf5 \
-DSLEPc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/slepc-3.9.1-24qjtyghv5yiizplwrfygywnjnxilk2t \
-DBUILD_DOC=ON
make
make doc_doxygen
```

**Comment by manavbhatia** [comment]
I like the more structured approach to finding packages through cmake. The idea of creating individual example executables is also good.

Concerning the addition of source code from the mast library to build an example, I would prefer to keep the original intent of the library: all the code in ```src/``` is intended to go into the ```mast``` library file. So, the examples can directly link to this. 

The original cmake script grabs all the source code in ```src``` (see [this](https://github.com/manavbhatia/mast-multiphysics/blob/002a8cd80a57203334f4e3feef0e0484673336c6/build/CMakeLists.txt#L122) line) and puts it into ```libmast```. It would be good to keep something similar, unless there is a strong reason to change.  

The documentation generation for examples can follow one fo two paths: either put all the doxygen comments in the example source code and parse these through utilities to create files that will directly create the example documentation that look like [this](https://dealii.org/9.0.0/doxygen/deal.II/step_1.html). Or to create individual documentation files for each example (in addition to the primary source files). I would prefer the former and we could take inspiration from deal.ii's [scripts](https://github.com/dealii/dealii/tree/master/doc/doxygen/scripts). 

The examples in the ```master``` branch are structured as individual files with minimal interdependencies. The ```topology``` branch attempted a more hierarchical approach, which you probably want to avoid. So, maybe we can start pulling the original examples into the new build system, unless you have other formats you want to use?

**Comment by jdeaton** [comment]
> Concerning the addition of source code from the mast library to build an example, I would prefer to keep the original intent of the library: all the code in `src/` is intended to go into the `mast` library file. So, the examples can directly link to this.
> 
> The original cmake script grabs all the source code in `src` (see [this](https://github.com/manavbhatia/mast-multiphysics/blob/002a8cd80a57203334f4e3feef0e0484673336c6/build/CMakeLists.txt#L122) line) and puts it into `libmast`. It would be good to keep something similar, unless there is a strong reason to change.

I think I might have mis-communicated this part earlier. I only added a couple of the MAST `src/xxx/xxx` files to get a basic target up and going. We should include all of them so that the fully functional `libmast` is built (according to requested options). However, I think we should do it using multiple `CMakeLists.txt` in sub-directories `src/xxx` and using the `target_sources(mast ...)` commands as opposed to the GLOB method at the top level. According to that book I quoted, this makes it easier when you ultimately use the "install" features of CMake to package up `libmast` and the headers and move them somewhere. For a particular build of `libmast`, we shouldn't attach any sources/headers to it for functionality that is turned off by a build option because the build process will incorporate unnecessary sources and more importantly the "install" process will package deploy headers that aren't functional. The top level GLOB indiscriminately adds everything to the target library.

For example, we collect the sources that provide the DOT interface in a directory `src/optimization/dot` and the `CMakeLists.txt` in that directory adds them to the mast target with `target_sources(mast dot_optimization_interface.h dot_optimization_interface.cpp)`. In the `CMakeLists.txt` one directory higher in `src/optimization` we just have:
```
if(ENABLE_DOT)
    add_subdirectory(dot)
endif()
```
Then if DOT functionality is turned off, the build process never even sees them and the resulting target doesn't have any of that information attached to it and it won't be deployed with a later `make install` during a Spack build for example.

I'll try to finish a new commit before we talk later with all of the sources packaged up in this more localized way in the current `src/xxx` subdirectories. We can think think about further discretizing based on build options if necessary.

**Comment by jdeaton** [comment]
> The documentation generation for examples can follow one fo two paths: either put all the doxygen comments in the example source code and parse these through utilities to create files that will directly create the example documentation that look like [this](https://dealii.org/9.0.0/doxygen/deal.II/step_1.html). Or to create individual documentation files for each example (in addition to the primary source files). I would prefer the former and we could take inspiration from deal.ii's [scripts](https://github.com/dealii/dealii/tree/master/doc/doxygen/scripts).

Also, I agree with you here. I previously took a look at how deal-ii was doing the documentation in the example sources and parsing them to create html. I think we should go that route.

**Comment by jdeaton** [comment]
Able to successfully build last commit to create full featured `libmast.a` (except optimization) with 
```
mkdir build2
cd build2
cmake .. \
-DCMAKE_C_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpicc \
-DCMAKE_CXX_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpicxx \
-DCMAKE_Fortran_COMPILER=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.2-lgkozytbuipvfz2bt77hwmd53hfe76eb/bin/mpifort \
-DlibMesh_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/libmesh-1.3.0-p5doeomab6c2lhay7ccxbglep4u7x44l \
-DPETSc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/petsc-3.9.3-e2zmceiit7nmkmtoohxv62dicnaqktf5 \
-DSLEPc_DIR=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/slepc-3.9.1-24qjtyghv5yiizplwrfygywnjnxilk2t \
-DBOOST_ROOT=/Users/deatonjd/Code/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/boost-1.68.0-myxjguveewn2ztb3quzkz734ndssqvob \
-DBUILD_DOC=OFF \
-DENABLE_DOT=OFF \
-DENABLE_GCMMA=OFF \
-DENABLE_NPSOL=OFF
make
```
I need to create CMake modules to find the external optimizer libraries and get it setup to link those libraries to the target if the options are turned on. I don't have those libraries on this computer (but I do have access to them to test).

I also think with this setup we don't need `src/base/mast_config.h.in` and related stuff in the optimizer interface sources files. Since CMake is handling whether or not to add the functionality we don't need the compiler to do it. I could be wrong though and there is another reason to keep it.

**Comment by manavbhatia** [comment]
This Cmake reconfig works fine when I call cmake configuration in the standard way (without the ```-G Xcode``` below). 

I am now trying to generate the Xcode build system with these options
```
cmake -G Xcode  ../../ \
-DCMAKE_C_COMPILER=mpicc-openmpi-clang \
-DCMAKE_CXX_COMPILER=mpicxx-openmpi-clang \
-DCMAKE_Fortran_COMPILER=mpif90-openmpi-clang \
-DlibMesh_DIR=~/Documents/codes/numerical/libmesh \
-DPETSc_DIR=~/Documents/codes/numerical/petsc \
-DSLEPc_DIR=~/Documents/codes/numerical/slepc \
-DBOOST_ROOT=/opt/local \
-DBUILD_DOC=OFF \
-DENABLE_DOT=OFF \
-DENABLE_GCMMA=OFF \
-DENABLE_NPSOL=OFF
``` 
and get the following errors
```
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
CMake Error at /opt/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.12/Modules/FindMPI.cmake:1666 (find_package_handle_standard_args)
  CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/manav/Documents/codes/inhouse/mast/mast_topology_cmake_update/build/xcode/CMakeFiles/CMakeOutput.log".
```

So, it picks up MPI_C in one case, and misses it in the other. This is a bit odd, since I am specifying the MPI commands in both cases. Is there a macro call that looks for MPI? 

Any clues why this may be happening?

**Comment by manavbhatia** [comment]
I should also mention that the previous build system works fine with the ```-G Xcode``` parameters. So, something about this Cmake update is messing up the MPI config macros. Also these macros appear to be provided by cmake in ```opt/local/share/cmake-3.12/Modules/FindMPI.cmake``` on my system. 

The [find_package(MPI REQUIRED)](https://github.com/jdeaton/mast-multiphysics/blob/011c531a6ae2a17003fe90af6ecd3e6ec42a1034/CMakeLists.txt#L29) command is calling the MPI macro in cmake. This did not exist in the original cmake config. Not sure why this would bomb with the ```-G Xcode``` parameter.

**Comment by manavbhatia** [comment]
Found some related discussion on the web for this behavior of cmake. This is fixed by the following: 

1. specify ``` -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx  ``` for Cmake configuration. 

2. Added a ```${MPI_CXX_INCLUDE_PATH}``` to ```target_include_directories```. 

This now works fine for both command line and Xcode builds.

**Comment by manavbhatia** [comment]
Found some related discussion on the web for this behavior of cmake. This is fixed by the following: 

1. specify ``` -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx  ``` for Cmake configuration. 

2. Added a ```${MPI_CXX_INCLUDE_PATH}``` to ```target_include_directories```. 

This now works fine for both command line and Xcode builds.

**Comment by manavbhatia** [comment]
I merged the PR into this branch [jdeaton-cmake-refactor](https://github.com/manavbhatia/mast-multiphysics/tree/jdeaton-cmake-refactor)

**Comment by manavbhatia** [comment]
Would it make sense to move the example from ```ex``` to ```examples``` so that we can start to migrate each to the new CMake system?

**Comment by jdeaton** [comment]
I think it makes sense to do that. I created an issue over on the main MAST repository to collect discussion related to examples: https://github.com/MASTmultiphysics/mast-multiphysics/issues/7.

I think we can close this pull-request. There's a few more things I'm going to try to do with CMake related to the installation part, which I need to finish the MAST spack package. I'll open a new pull request against https://github.com/manavbhatia/mast-multiphysics/tree/jdeaton-cmake-refactor when I get it figured out.

**Comment by manavbhatia** [comment]
Pulled the changes into branch [jdeaton-cmake-refactor](https://github.com/manavbhatia/mast-multiphysics/commit/4463f0c2043d54ceb4f543ae4b0b6a0c331c85be).

**Pull request closed without merging**
